repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: e19917ae62c365d4d746fa9639c7506435bcf1c8
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
        args:
        - --exclude=*/*migrations/*, testproject/testproject/settings/*
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: b57843b0b874df1d16eb0bef00b868792cb245c2
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
