repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: e19917ae62c365d4d746fa9639c7506435bcf1c8
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
        args:
        - --exclude=*/*migrations/*, testproject/testproject/settings/*
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3
