cache: pip

language: python

matrix:
  include:
  - python: 3.5
    dist: xenial
    sudo: false
    env: DJANGO="2.1"
  - python: 3.5
    dist: xenial
    sudo: false
    env: DJANGO="2.2"

  - python: 3.6
    dist: xenial
    sudo: false
    env: DJANGO="2.1"
  - python: 3.6
    dist: xenial
    sudo: false
    env: DJANGO="2.2"
  - python: 3.6
    dist: xenial
    sudo: false
    env: DJANGO="3.0"

  - python: 3.7
    dist: xenial
    sudo: false
    env: DJANGO="2.1"
  - python: 3.7
    dist: xenial
    sudo: true
    env: DJANGO="2.2"
  - python: 3.7
    dist: xenial
    sudo: true
    env: DJANGO="3.0"

  - python: 3.8
    dist: xenial
    sudo: false
    env: DJANGO="2.1"
  - python: 3.8
    dist: bionic
    sudo: true
    env: DJANGO="2.2"
  - python: 3.8
    dist: bionic
    sudo: true
    env: DJANGO="3.0"

  - python: pypy
    dist: trusty
    sudo: false
    env: DJANGO="2.2"
  - python: pypy
    dist: trusty
    sudo: false
    env: DJANGO="3.0"

install:
  - pip install tox tox-travis coverage codecov

script:
  - tox

notifications:
    irc:
    - "irc.freenode.org#django-wiki"

after_success:
  - coverage combine
  - codecov
