language: python
# See tox.ini for env list
env:
- TOXENV=py26-django14
- TOXENV=py26-django15
- TOXENV=py26-django16
- TOXENV=py27-django14
- TOXENV=py27-django15
- TOXENV=py27-django16
- TOXENV=py27-django17
- TOXENV=py33-django15
- TOXENV=py33-django16
- TOXENV=py33-django17
- TOXENV=py34-django15
- TOXENV=py34-django16
- TOXENV=py34-django17
install:
- pip install tox
script:
- tox
notifications:
    irc:
        - "irc.freenode.org#django-wiki"
