# Because Python 3.6 is available on GCE
dist: trusty

cache: pip

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - LINT="yes"
  - DJANGO="1.11"

matrix:
  exclude:
  - python: "3.4"
    env: LINT="yes"
  - python: "3.5"
    env: LINT="yes"
  - python: "3.6"
    env: LINT="yes"

install:
  - pip install tox tox-travis coverage codecov

script:
  - tox

notifications:
    irc:
        - "irc.freenode.org#django-wiki"

after_success:
  - coverage combine
  - codecov
